### ISSUE TITLE
no app.json file, can not run in weixin

### ISSUE THREAD

**Issue by lihaoqi1991** [yllg/mpvue-xbyjShop#1]
after npm run build, no app.json file, can not run in weixin

**Comment by yllg** [comment]
已经修复。
删除package.json文件中"mpvue-loader": "^1.0.13",里面的‘^’，再npm install、npm run dev即可。
原因：^1.0.13，会安装>=1.0.13和 <2.0.0之间的最新版本，造成新版本不兼容而编译不成功。
