### ISSUE TITLE
地址选择存在滚动穿透问题

### ISSUE THREAD

**Issue by zhuwenbing** [yllg/mpvue-xbyjShop#5]
作者你好，今天在使用中发现一个问题，就是在真机上下单后新增收货地址的时候，发现这里有个滚动穿透的问题：具体表现为地址选择弹出层向上滚动没问题，向下就不能滚动了而是直接变成刷新页面了。

**Comment by wickedcode01** [comment]
你能购买吗？我怎么看到购买按钮里面连点击事件都没有，就是个死按钮。

**Comment by liangjinghao6** [comment]
没试过，我主要用的是前段的东西，其他的都是自己开发




------------------ 原始邮件 ------------------
发件人: "JIMMY-YEN"<notifications@github.com>;
发送时间: 2019年1月2日(星期三) 晚上8:24
收件人: "yllg/mpvue-xbyjShop"<mpvue-xbyjShop@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [yllg/mpvue-xbyjShop] 地址选择存在滚动穿透问题 (#5)




你能购买吗？我怎么看到购买按钮里面连点击事件都没有，就是个死按钮。
